### ISSUE TITLE
4.18 Change to PreGarbageCollectDelegate for dev branch code

### ISSUE THREAD

**Issue by SonicZentropy** [asqbtcupid/unreal.lua#12]
Just FYI since I tracked it down - in TableUtil.cpp a couple times FCoreObjectDelegates::PreGarbageCollectDelegate is used, but 4.18 has refactored that into FCoreUObjectDelegates::GetPreGarbageCollectDelegate()

Making that one change appears all that's necessary to fix build for 4.18.

Plays in editor with that change, though there is a problem with luahotupdate not finding files from HU.FileMap that I haven't tracked down yet.  Looks like HU.FileMap just isn't being loaded with them at all

**Comment by asqbtcupid** [comment]
thanks,most time,i work with 4.17 engine,Then test it with another version engine.So i will miss something in 4.18.

for luahotupdate,you shouldn't touch anything but hotupdatelist.lua,Add filename to it to update this file.Only update function logic,but maybe failure.

**Comment by asqbtcupid** [comment]
fixed
