### ISSUE TITLE
some kind of enum type can not be export

### ISSUE THREAD

**Issue by mirchd** [asqbtcupid/unreal.lua#15]
such as, in WidgetComponent.h
UENUM(BlueprintType)
enum class EWidgetSpace : uint8
{
	/** The widget is rendered in the world as mesh, it can be occluded like any other mesh in the world. */
	World,
	/** The widget is rendered in the screen, completely outside of the world, never occluded. */
	Screen
};

protected:
	/** The coordinate space in which to render the widget */
	UPROPERTY(EditAnywhere, Category=UserInterface)
	EWidgetSpace Space;

export: in WidgetComponent.script.h
static int32 UWidgetComponent_Set_Space(lua_State* L)
{
	UWidgetComponent* Obj = (UWidgetComponent*)UTableUtil::tousertype("UWidgetComponent",1);
	return 0;
}

~please help

**Comment by asqbtcupid** [comment]
new version is ok.WidgetComponent.script.h is renamed to WidgetComponent.lua.h.

**Comment by mirchd** [comment]
thanks
