### ISSUE TITLE
luacallr when the type of return value is struct, compile error

### ISSUE THREAD

**Issue by mirchd** [asqbtcupid/unreal.lua#16]
my struct:
USTRUCT()
struct FFormation
{
	GENERATED_BODY()

	FFormation()
	{

	}

	// sort
	UPROPERTY()
	TArray<FBattleShip>	sortShipArr;
};

when compile at "luacallr(FFormation, ...." 
it match
template<class T>
static T popinternal(lua_State *L, int index, typename TEnableIf< TIsSame<typename traitstructclass<T>::NotStructType, NotNeedTempInsType>::Value,T>::Type* pp = nullptr )
{
	return (T)ue_lua_tointeger(L, index);
};

please help

**Comment by asqbtcupid** [comment]
you have to #include "Formation.lua.h", struct is special.

**Comment by mirchd** [comment]
it is resolved, thanks

**Comment by mirchd** [comment]
and subclass<someActor> also compile error.
UCLASS()
class AArmyShipActor : public AActor
{
	GENERATED_BODY()

public:
	UPROPERTY(EditDefaultsOnly, Category = "CannonFire")
	TSubclassOf<AMissileActor> ProjectileClass;
};

class AMissileActor : public AActor

when link, it says " AMissileActor::GetPrivateStaticClass can be find,

**Comment by asqbtcupid** [comment]
UCLASS()
class YOUR_GAMEMODULE_API AArmyShipActor : public AActor
{
GENERATED_BODY()
}

your class is not a api class, you should add YOUR_GAMEMODULE_API macro.Have a look to engine's class declaration.

**Comment by mirchd** [comment]
it is ok~thank you very much

**Comment by mirchd** [comment]
Is LuaDebugger plugin can be used in visual studio? and may I debug lua in ue4?

**Comment by asqbtcupid** [comment]
in ue4 editor, click windows -> LuaDebugger.Then open the debugger.

**Comment by mirchd** [comment]
thanks,I'll try it~
