### ISSUE TITLE
Can I get the pointer of the table represented object?

### ISSUE THREAD

**Issue by RPG3D** [asqbtcupid/unreal.lua#26]
In most case, I want to call a C++ function in lua, and the C++ function need a pointer, such as UGameplayStatics::GetGameInstance(UObject* WorldContext),  and in GameMode.lua, the self is a table? how can I get the light userdata of GameMode?

**Comment by asqbtcupid** [comment]
you can just pass the table to the function.The framework will switch the table to the c++ object.

and self._cppinstance_ is the c++ object.
