### ISSUE TITLE
能解說一下您是怎麼讓處理與管理UE4與Lua的內存和垃圾回收機制嗎？

### ISSUE THREAD

**Issue by stevefan1999-personal** [asqbtcupid/unreal.lua#27]
我也想弄一個UE4腳本😝。

但是面對UE4的GC物件機制我無從入手...因為虛擬機與UE4 NewObject的內存完全分離，兩邊都有自己的堆和根呀...如果我Lua那邊New了一個新物件，我應該讓Unreal回收還是Lua標記管理？如果C++那邊管了Lua的Object怎麼辦？

而且我覺得做多線程時，這尤其會有衝突...我覺得唯一的解決方法就是Lua虛擬機只可以執行純函數...

還有呢，怎麼樣處理Lua的組態？總不能每一個物件都配一個lua_State吧？如果我弄了1000個Entity這不就死得了...更何況這有機會造成內存洩漏...但是用全局Lua組態又不安全...有機會造成PIE崩潰和令某些物件不死...

BP我沒有怎麼看過，太複雜了。

另外我想問是怎麼樣實現Lua衍生的UObject反射？例如我在Lua弄了一個組函數我想把它反射出去然後在C++裏用UObject::FindFunction然後創建FFrame最後呼叫可以嗎？UE4的反射重建UHT太操蛋了...

順帶一提，我是想用TypeScript的。

**Comment by asqbtcupid** [comment]
lua里引用的Object，c++无法回收，所以只需要在lua里管理好就行。

多线程的话还真是没办法，只能在lua虚拟机里加锁了。

应该是可以的，这个可以参考一下unreal.js，如果你想用typescript。

**Comment by stevefan1999-personal** [comment]
哈哈...Unreal.js也有點難讀呀...而且用的是V8，又太工程過度了，加上我要多平台，所以我才轉至研究其他UE4腳本實現。

對啊...像Python一樣GIL加鎖，不過就是可能慢了點。

但是虛擬機那邊弄了一個原生C++的物件(譬如AActor派生系)，那虛擬機和Unreal這邊都有應該一個引用？我這樣想是因為如果虛擬機摧毀了物件，C++那邊會出現野指針的情況，要是這樣我就乾脆兩邊都綁定一個引用了而且以Unreal的內存管理為主。
虛擬機向C++要求指針並強制加入Unreal物件根組合，虛擬機在內部進行象徵式的計數。就是當虛擬機摧毀物件時才將物件釋放到正常內存，給Unreal物件管理器重新使用並永不重取。雖然這樣有機會導致額外的內存無法正常回收（後果可以很大，會出現信息洩露，亦會導致移動平台容易內存不足），也可能性能較低（注定要N+1個回收迴圈，比原生物件回收遲一步），但肯定不會導致指針無效，指針也可以C++和虛擬機之間共享了。

也決定了用全局變量，但是虛擬機對每個派生物件USciptedObject綁定一個虛擬機實例，也會綁定UWorld，畢竟是要避免PIE和無縫轉折時的內存衝突呀。

還是惡補一下InsideUE4🤣

最後要想像的問題就是物件關係了，尤其是繼承的父子建構解構器等煩人的細節...

**Comment by asqbtcupid** [comment]
如果用脚本了就不要太在意追求性能极限，而应该注重易用性，当提高了开发效率之后，省下来时间在做性能优化，逻辑占的CPU不多，加锁也没关系，如果影响了你的性能，可以尝试换种架构，问题未必出在脚本上。
我现在的内存管理跟你想的差不多，lua引用的情况下，c++不回去回收这块内存。

多个PIE也是比较令人头疼，主要是易用性降低了，每次都得找到world再找虚拟机，这个需要你自己考虑，不仅是在lua，在c++上做单例系统也有这个问题。

如果要基于UE4做继承，在BlueprintGeneratedClass上做手脚，要考虑的事情也很多，可以看看unreal.js,它做了很好的示范。我这边考虑到lua的特性，尽量是做得简单够用，不侵入c++和蓝图。
