### ISSUE TITLE
ue4.20 compile error?

### ISSUE THREAD

**Issue by mirchd** [asqbtcupid/unreal.lua#29]
is the plugin will upgrade to 4.20?
thanks

**Comment by asqbtcupid** [comment]
sorry, i don't have time recently.maybe i will update it one or two month later.

**Comment by mirchd** [comment]
26>LogModuleManager : warning : ModuleManager: Unable to load module 'LuaglueGenerator' - 0 instances of that module name found.
26>LogCompile : error : Failed to inittialize the engine (PreInit failed).

please help,

**Comment by asqbtcupid** [comment]
i don't have time and tool until weekend

**Comment by mirchd** [comment]
4.20 had been released, may you has time to update the plugin, thank you.

**Comment by asqbtcupid** [comment]
i will solve it this weekend.

**Comment by mirchd** [comment]
Is there any new progress?

**Comment by asqbtcupid** [comment]
wuwuwuwu~sorry,i will solve it as soon as possible.

**Comment by SuperBrentLee** [comment]
hi,the plugin is very good!  I want to use it in project, but 4.20 can't do, Could u help me?

**Comment by asqbtcupid** [comment]
sorry about it. i will solve it as soon as possible,maybe this weekend.

**Comment by SuperBrentLee** [comment]
thank u very much.

**Comment by asqbtcupid** [comment]
https://github.com/asqbtcupid/unreal.lua/tree/4.20, move the LuaGlueGenerator folder to Engine/Plugins. only tested in windows with source compiled engine.

**Comment by mirchd** [comment]
thanks, I'll try it.

**Comment by mirchd** [comment]
13>  Running UnrealHeaderTool "D:\Unreal\unreal.lua\CatchMe.uproject" "D:\Unreal\unreal.lua\Intermediate\Build\Win64\CatchMeEditor\Debug\CatchMeEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
13>LogModuleManager : warning : ModuleManager: Unable to load module 'LuaglueGenerator'  - 0 instances of that module name found.
13>LogCompile : error : Failed to initialize the engine (PreInit failed).
13>EXEC : error : UnrealHeaderTool failed for target 'CatchMeEditor' (platform: Win64, module info: D:\Unreal\unreal.lua\Intermediate\Build\Win64\CatchMeEditor\Debug\CatchMeEditor.uhtmanifest, exit code: CrashOrAssert (3)).

**Comment by rafadsm** [comment]
I have the same problem :(
The plugin LuaGlueGenerator not compiled
