### ISSUE TITLE
版本4.14 编译不过

### ISSUE THREAD

**Issue by albus0x01** [asqbtcupid/unreal.lua#3]
RT。

**Comment by asqbtcupid** [comment]
请问是编辑器版本，还是源码版本？

**Comment by albus0x01** [comment]
源码和编辑器版本都编译不过。

**Comment by asqbtcupid** [comment]
你可以先试试demo_firstperson_umg这个分支，因为有些东西东西需要手改，具体怎么改可以看看这个https://github.com/asqbtcupid/unreal.lua/wiki/1.Installation。

**Comment by cty41** [comment]
恩，我下了umg分支在4.14下是可运行的，赞一个！
4.15涉及到c++编译优化，目前编译报错。
大概看了下结构，感觉是不是将来把LuaPlugin抽离出game project，（LuaPlugin项目+UEToLuaGlueCodeLib项目）是不是这样会更灵活一些？

**Comment by asqbtcupid** [comment]
@cty41 感谢关注，目前只实现了最基本的东西，更像是验证了一下lua开发的可行性，真正用来做项目还是有所欠缺。我打算再深入学习一段时间虚幻4，然后重新写一下，让lua能跟虚幻更紧密的结合在一起，用起来更舒服。

**Comment by cty41** [comment]
回复好快，哈哈哈。我也是有这个计划，本来想自己学着写个lua插件的，但先搜到也是国人的你写的这个了，不过显然你比我快了不少：）我想一块来完善这个插件，你看咋样

**Comment by asqbtcupid** [comment]
可以啊，最近我试着用unreal.lua来做自己的小demo，发现一些不好用的地方，然后做了一点修改，我们可以从这个版本开始完善，我晚上上传一下。我的QQ是285291946，方便的话加一下好沟通。
