### ISSUE TITLE
能否把LuaGeneratedCode生成到Intermediate\Build\Platform下面

### ISSUE THREAD

**Issue by gamebili** [asqbtcupid/unreal.lua#30]
切换多平台编译的时候很麻烦，要删除原先的LuaGeneratedCode重新生成，建议不同平台生成在不同的位置。

**Comment by asqbtcupid** [comment]
没事，你们随便改，我暂时没有时间维护这个项目了。还有就是现在给公司做的比这个先进了很多，但是闭源了，不好维护这个了。

**Comment by gamebili** [comment]
了解。
