### ISSUE TITLE
打包在真机运行的问题

### ISSUE THREAD

**Issue by Huangjianan** [asqbtcupid/unreal.lua#31]
你好，打包到真机上的时候，LuaSource应该是找不到的，所以main找不到会崩溃，看nativeluafunc.h里main应该是通过loadobject<uluascript>加载的，这块有需要额外设置什么吗？
我看了代码能想到的是把LuaSource放到Content目录下，然后在打包设置Additional Non-Asset Directories to Package里面加上LuaSource，然后在GetLuaCodeFromPath函数里从打包文件里读出来。这样应该是可以在真机打包里拿到。
但我不知道你的工程这里是不是已经有某种别的办法？  期待并感谢你的回答。

**Comment by asqbtcupid** [comment]
打开编辑器，把LuaSource拽进Content目录，就会生成uasset，把这个打进包里就行了。

**Comment by Huangjianan** [comment]
懂了，谢谢了~
