### ISSUE TITLE
引擎源码版本编译不过，折腾了很久，作者你有遇到过么

### ISSUE THREAD

**Issue by ren19890419** [asqbtcupid/unreal.lua#32]
3>EXEC : error : Can't save a makefile that has invalid contents.  See UBTMakefile.IsValidMakefile()
3>       (see ..\Programs\UnrealBuildTool\Log_UHT.txt for full exception trace)
ERROR: Can't save a makefile that has invalid contents.  See UBTMakefile.IsValidMakefile()

另外反射版本哪个链接打开提示404 找不到git地址

**Comment by asqbtcupid** [comment]
哪一个版本引擎啊？ 反射版本闭源了

**Comment by ren19890419** [comment]
我用的引擎4.20版本，	"Plugins": [
		{
			"Name": "LuaPlugin",
			"Enabled": false
		}
"Enabled": false 的时候编译没有问题，设置成true就编译不过。

**Comment by asqbtcupid** [comment]
目前这个插件最新只支持到4.19。暂时没有精力升级了，不好意思。
