### ISSUE TITLE
restartlevel lead to crash

### ISSUE THREAD

**Issue by gamebili** [asqbtcupid/unreal.lua#5]
enter console command "restartlevel", then the game crashed. Crash message
" World /Game/TestMap.TestMap not cleaned up by garbage collection! "

**Comment by asqbtcupid** [comment]
Fix it.maintain gc reference between two VM is a challenge work.In unreal.lua, If you reference an UObject pointer in lua,It won't be garbarge collected by c++.I made a mistake in cppobjectbase.lua.
