### ISSUE TITLE
UE4.18 support

### ISSUE THREAD

**Issue by DsoTsin** [asqbtcupid/unreal.lua#6]
UAssetObjectProperty has been renamed to USoftObjectProperty

**Comment by asqbtcupid** [comment]
I'm Refactoring this plugin.I will move the runtime part from gamemodule to pluginmodule,make it become a real plugin.And I try to avoid generate big .cpp file to decrease the compilation time.It will cost me one or two week.After that i will update it to support 4.18, Thank you.

**Comment by asqbtcupid** [comment]
fixed
