### ISSUE TITLE
allweakclass.script.h

### ISSUE THREAD

**Issue by mirchd** [asqbtcupid/unreal.lua#7]
error C2011: “TWeakObjectPtr_UObject”:“class” type redifinition?
when I add a new class in a new file to my project, then build solution, some errors occur in visual studio 2017?

**Comment by mirchd** [comment]
void FLuaScriptCodeGenerator::ExportEnum()

need add #pragma once in the header file

and 

void FLuaScriptCodeGenerator::GenerateWeakClass()

also need add #pragma once in the header file str

FString GeneratedGlue;
	FString TraitGlue = TEXT("#pragma once\r\ntemplate<class T>\r\nclass traitweakclass{};\n");
-->
FString GeneratedGlue;
	FString TraitGlue = TEXT("#pragma once\r\n");

can avoid this error for redifinition.

**Comment by asqbtcupid** [comment]
thank you for solve this bug.I'm refactoring this plugin,It will have a huge improvement,Thanks for your attention.
